// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy44hp_ModvKKgiPq1XkTMjTwdRIrxH_g',
    appId: '1:209443261076:web:16920dfdf9c4ddc2168281',
    messagingSenderId: '209443261076',
    projectId: 'flutterproject-209f1',
    authDomain: 'flutterproject-209f1.firebaseapp.com',
    storageBucket: 'flutterproject-209f1.appspot.com',
    measurementId: 'G-DKMNMFKY0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnvLC623q0NvCmQTELOiBTZVIrQWQ0h2U',
    appId: '1:209443261076:android:87b5c552110859c8168281',
    messagingSenderId: '209443261076',
    projectId: 'flutterproject-209f1',
    storageBucket: 'flutterproject-209f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQQM85IatR_BOhpjU9X4zioLMt9ddPu8',
    appId: '1:209443261076:ios:4f0e44d628541b17168281',
    messagingSenderId: '209443261076',
    projectId: 'flutterproject-209f1',
    storageBucket: 'flutterproject-209f1.appspot.com',
    iosClientId: '209443261076-r44httu1pgjvp2uoj2sfmm8efmusd8k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQQM85IatR_BOhpjU9X4zioLMt9ddPu8',
    appId: '1:209443261076:ios:4f0e44d628541b17168281',
    messagingSenderId: '209443261076',
    projectId: 'flutterproject-209f1',
    storageBucket: 'flutterproject-209f1.appspot.com',
    iosClientId: '209443261076-r44httu1pgjvp2uoj2sfmm8efmusd8k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
